[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Static site deployment'"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"